namespace RestaurantApi.Models.Dtos
{
    public class TableDto // Primarily for reading, generated by backend
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
    }
}
